#!/bin/bash
# HomeStack — Secrets management
# Generates and prompts for secrets at install time

# Generate a random password of given length
generate_password() {
  local length="${1:-32}"
  tr -dc 'A-Za-z0-9!@#%^*_-' < /dev/urandom | head -c "$length" 2>/dev/null || \
  openssl rand -base64 "$length" | tr -dc 'A-Za-z0-9' | head -c "$length"
}

# Generate secrets.env for an app from its app.yaml
# Usage: generate_secrets_file <app_yaml_path> <output_secrets_env_path>
generate_secrets_file() {
  local app_yaml="$1"
  local output="$2"
  local app_name
  app_name=$(yaml_get "$app_yaml" "name")

  local secrets_data
  secrets_data=$(yaml_parse_secrets "$app_yaml")

  if [[ -z "$secrets_data" ]]; then
    # No secrets needed — create empty file
    echo "# No secrets required for ${app_name}" > "$output"
    return 0
  fi

  echo -e "${BLUE}Configure secrets for ${app_name}:${NC}"
  echo ""

  local entries=()

  while IFS='|' read -r key prompt default_val generate length; do
    local value=""

    if [[ "$generate" == "true" ]]; then
      value=$(generate_password "$length")
      echo -e "  ${GREEN}${key}${NC}: auto-generated (${length} chars)"
    elif [[ -n "$default_val" ]]; then
      echo -ne "  ${key}"
      echo -ne " [${default_val}]: "
      read -r user_input
      value="${user_input:-$default_val}"
    else
      echo -ne "  ${key}"
      [[ -n "$prompt" ]] && echo -ne " (${prompt})"
      echo -ne ": "
      read -r value
      while [[ -z "$value" ]]; do
        echo -ne "  ${RED}Required.${NC} ${key}: "
        read -r value
      done
    fi

    entries+=("${key}=${value}")
  done <<< "$secrets_data"

  echo ""

  # Write secrets file
  {
    echo "# Secrets for ${app_name}"
    echo "# Auto-generated by homestack install — $(date +%Y-%m-%d)"
    echo ""
    for entry in "${entries[@]}"; do
      echo "$entry"
    done
  } > "$output"

  success "Secrets written to $(basename "$output")"
}
