"""HomeStack — Secret generation and management."""

from __future__ import annotations

import os
import string
from pathlib import Path

import click

from homestack import core
from homestack.yaml_parser import parse_secrets, SecretDef


def generate_password(length: int = 32) -> str:
    """Generate an alphanumeric password of *length* characters."""
    import secrets as _secrets
    alphabet = string.ascii_letters + string.digits
    return "".join(_secrets.choice(alphabet) for _ in range(length))


def generate_secrets_file(app_yaml: str | Path, output: str | Path,
                          *, interactive: bool = True) -> None:
    """Create a ``secrets.env`` file from the secrets block in *app_yaml*.

    For secrets with ``generate: true``, a random password is created.
    For secrets with a ``default``, the user is prompted with that default
    (unless *interactive* is False, in which case the default is used directly).
    For secrets with neither, the user is prompted for input (hidden).
    """
    secrets = parse_secrets(app_yaml)
    output = Path(output)

    if not secrets:
        output.write_text(f"# No secrets required\n")
        os.chmod(output, 0o600)
        return

    from homestack.yaml_parser import yaml_get
    app_name = yaml_get(str(app_yaml), "name")
    click.echo(click.style(f"Configure secrets for {app_name}:", fg="blue", bold=True))
    click.echo()

    entries: list[str] = []

    for s in secrets:
        if s.generate:
            value = generate_password(s.length)
            click.echo(click.style(f"  {s.key}", fg="green") + f": auto-generated ({s.length} chars)")
        elif s.default:
            if interactive:
                value = click.prompt(f"  {s.key}", default=s.default)
            else:
                value = s.default
                click.echo(f"  {s.key}: {value}")
        else:
            if interactive:
                prompt_text = f"  {s.key}"
                if s.prompt:
                    prompt_text += f" ({s.prompt})"
                value = click.prompt(prompt_text, hide_input=True)
                while not value:
                    click.echo(click.style("  Required.", fg="red"), nl=False)
                    value = click.prompt(f" {s.key}", hide_input=True)
            else:
                value = generate_password(16)  # fallback for non-interactive
                click.echo(click.style(f"  {s.key}", fg="green") + ": auto-generated (16 chars)")

        entries.append(f'{s.key}={value}')

    click.echo()

    lines = [
        f"# Secrets for {app_name}",
        f"# Auto-generated by homestack install",
        "",
    ] + entries + [""]

    output.write_text("\n".join(lines))
    os.chmod(output, 0o600)
    core.success(f"Secrets written to {output.name}")


def append_new_secrets(app_yaml: str | Path, secrets_file: str | Path,
                       *, interactive: bool = True) -> None:
    """Append new secret keys that don't exist in *secrets_file*.

    Used during ``homestack update`` to add secrets introduced in a new
    catalog version without overwriting existing values.
    """
    secrets = parse_secrets(app_yaml)
    if not secrets:
        return

    secrets_path = Path(secrets_file)
    existing_text = secrets_path.read_text() if secrets_path.is_file() else ""
    existing_keys = set()
    for line in existing_text.splitlines():
        if "=" in line and not line.strip().startswith("#"):
            existing_keys.add(line.split("=", 1)[0].strip())

    new_secrets = [s for s in secrets if s.key not in existing_keys]
    if not new_secrets:
        return

    from homestack.yaml_parser import yaml_get
    app_name = yaml_get(str(app_yaml), "name")
    click.echo(click.style(f"New secrets required for {app_name}:", fg="yellow"))
    click.echo()

    new_lines: list[str] = []
    for s in new_secrets:
        if s.generate:
            value = generate_password(s.length)
            click.echo(click.style(f"  {s.key}", fg="green") + f": auto-generated ({s.length} chars)")
        elif s.default:
            if interactive:
                value = click.prompt(f"  {s.key}", default=s.default)
            else:
                value = s.default
                click.echo(f"  {s.key}: {value}")
        else:
            if interactive:
                prompt_text = f"  {s.key}"
                if s.prompt:
                    prompt_text += f" ({s.prompt})"
                value = click.prompt(prompt_text, hide_input=True)
                while not value:
                    click.echo(click.style("  Required.", fg="red"), nl=False)
                    value = click.prompt(f" {s.key}", hide_input=True)
            else:
                value = generate_password(16)
                click.echo(click.style(f"  {s.key}", fg="green") + ": auto-generated (16 chars)")

        new_lines.append(f'{s.key}={value}')

    click.echo()

    with open(secrets_path, "a") as f:
        for line in new_lines:
            f.write(line + "\n")

    core.success(f"New secrets appended to {secrets_path.name}")
